# Generated by Django 5.1.5 on 2025-01-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='assigned_users',
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lead_team', models.ManyToManyField(related_name='lead_team', to='api.employeemodel')),
            ],
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='assigned_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.leadmodel'),
        ),
    ]
