# Generated by Django 5.1.5 on 2025-01-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_projectmodel_assigned_users_leadmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='assigned_users',
            new_name='assigned_lead',
        ),
    ]
