# Generated by Django 5.1.5 on 2025-02-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tickettags_ticketmodel_ticketheadings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketheadings',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketheadings',
            name='ticket',
            field=models.ManyToManyField(blank=True, null=True, to='api.ticketmodel'),
        ),
    ]
