# Generated by Django 5.1.5 on 2025-02-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_ticketheadings_ticket_ticketheadings_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='ticket_tags', to='api.tickettags'),
        ),
    ]
