# Generated by Django 5.1.5 on 2025-02-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ticketmodel_extra_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='assigned_employee',
            field=models.ManyToManyField(related_name='assigned_employee', to='api.employeemodel'),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projectmodel'),
        ),
    ]
