# Generated by Django 5.1.5 on 2025-02-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticketmodel_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketheadings',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
