# Generated by Django 5.1.5 on 2025-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employeemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='assigned_employee',
            field=models.ManyToManyField(to='api.employeemodel'),
        ),
    ]
