# Generated by Django 5.1.5 on 2025-02-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_projectmodel_assigned_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketHeadings',
        ),
    ]
